# Generated by Django 6.0 on 2025-12-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='youtube_channel_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
