# Generated by Django 6.0 on 2025-12-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_personalinfo_youtube_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/'),
        ),
    ]
