# Generated by Django 6.0 on 2025-12-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_personalinfo_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='kofi_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
