# Generated by Django 6.0 on 2025-12-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('date_range', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('work', 'Work'), ('education', 'Education'), ('school', 'School Activities'), ('certifications', 'Certifications')], max_length=20)),
                ('link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
