# Generated by Django 6.0 on 2025-12-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qualification',
            options={'ordering': ['-end_date', '-start_date']},
        ),
        migrations.AddField(
            model_name='qualification',
            name='end_date',
            field=models.DateField(blank=True, help_text="Leave blank for 'Present'", null=True),
        ),
        migrations.AddField(
            model_name='qualification',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
