# Generated by Django 6.0 on 2025-12-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualifications', '0002_alter_qualification_options_qualification_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qualification',
            options={'ordering': [models.OrderBy(models.F('end_date'), descending=True, nulls_first=True), '-start_date']},
        ),
    ]
