# Generated by Django 6.0 on 2025-12-19 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qualifications', '0003_alter_qualification_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='date_range',
        ),
    ]
